inpt = ["pale turquoise bag:3 muted cyan bag, 5 striped teal bag",
"light tan bag:5 posh tomato bag",
"shiny coral bag:2 muted bronze bag",
"wavy orange bag:4 faded tomato bag",
"light plum bag:3 drab orange bag, 4 faded coral bag",
"pale purple bag:5 bright crimson bag",
"bright blue bag:1 pale beige bag, 1 light teal bag",
"pale bronze bag:1 dotted salmon bag, 1 striped blue bag, 2 clear tan bag",
"muted maroon bag:5 pale crimson bag",
"clear lavender bag:4 vibrant black bag, 2 posh red bag",
"pale cyan bag:4 light olive bag, 2 dull lime bag, 4 faded black bag, 4 plaid red bag",
"faded blue bag:1 posh tan bag, 1 dotted violet bag, 3 posh gold bag",
"wavy teal bag:3 pale brown bag",
"striped red bag:2 light bronze bag, 3 dark cyan bag",
"drab brown bag:3 striped magenta bag, 3 clear silver bag",
"posh salmon bag:4 bright purple bag, 5 mirrored green bag, 3 pale gold bag, 5 dull crimson bag",
"light black bag:2 wavy coral bag",
"striped tan bag:3 clear blue bag, 3 mirrored teal bag, 5 striped red bag",
"posh plum bag:3 drab orange bag",
"striped blue bag:4 bright violet bag, 5 dotted gray bag, 3 dotted violet bag, 1 dotted blue bag",
"shiny white bag:4 dotted orange bag, 1 faded silver bag, 1 drab coral bag",
"plaid maroon bag:3 light gold bag",
"shiny fuchsia bag:2 dotted olive bag, 3 vibrant white bag, 3 dark salmon bag, 4 pale white bag",
"muted bronze bag:4 vibrant bronze bag, 2 posh yellow bag, 1 shiny turquoise bag",
"wavy cyan bag:2 striped crimson bag, 4 plaid tan bag",
"vibrant indigo bag:4 pale gold bag, 3 posh gold bag, 1 drab red bag, 4 dull crimson bag",
"drab tan bag:3 dark indigo bag, 3 striped black bag",
"dull tan bag:3 drab blue bag, 3 pale green bag, 3 dotted red bag, 3 striped maroon bag",
"dark red bag:4 bright chartreuse bag",
"drab beige bag:5 bright teal bag, 1 faded cyan bag, 2 muted yellow bag, 1 dim lime bag",
"dim black bag:5 wavy fuchsia bag, 3 muted tomato bag, 4 faded blue bag",
"pale red bag:2 drab gray bag, 5 dull coral bag, 4 striped purple bag",
"light cyan bag:4 mirrored gold bag, 3 vibrant bronze bag",
"posh orange bag:2 dark silver bag, 3 striped chartreuse bag",
"shiny cyan bag:5 dark turquoise bag",
"vibrant cyan bag:2 light turquoise bag, 2 clear cyan bag, 4 dark cyan bag, 4 dotted orange bag",
"vibrant gray bag:5 dark purple bag, 5 dark lime bag",
"posh green bag:4 bright salmon bag, 2 muted tan bag",
"posh tan bag:2 dotted indigo bag, 1 dull purple bag",
"clear blue bag:5 dull purple bag",
"wavy gray bag:4 pale cyan bag, 2 pale tomato bag",
"posh red bag:4 dim green bag, 2 pale teal bag",
"light tomato bag:5 dotted chartreuse bag",
"faded yellow bag:3 plaid orange bag, 4 mirrored maroon bag",
"dark black bag:1 faded gold bag, 3 striped purple bag, 2 dim teal bag",
"light red bag:5 dark magenta bag, 3 striped purple bag",
"dotted violet bag:x",
"faded gold bag:1 dotted aqua bag, 2 light turquoise bag, 5 wavy violet bag",
"dotted beige bag:5 vibrant turquoise bag, 5 clear maroon bag, 3 dim tomato bag, 4 pale maroon bag",
"pale lavender bag:5 muted red bag, 3 dark teal bag, 3 faded black bag, 1 dim fuchsia bag",
"clear tomato bag:3 dull white bag, 3 mirrored gold bag, 1 dark black bag",
"vibrant silver bag:4 plaid orange bag, 2 shiny chartreuse bag, 3 dark salmon bag, 4 light silver bag",
"plaid cyan bag:1 dark black bag",
"drab green bag:1 plaid white bag",
"posh turquoise bag:3 posh plum bag, 3 light gold bag, 1 bright crimson bag",
"pale lime bag:3 pale olive bag, 3 vibrant chartreuse bag, 1 dotted tan bag, 5 striped cyan bag",
"wavy fuchsia bag:3 shiny chartreuse bag, 3 vibrant tomato bag, 3 posh salmon bag, 1 light cyan bag",
"shiny beige bag:1 muted orange bag, 3 clear olive bag",
"posh tomato bag:5 muted tomato bag, 5 drab coral bag, 4 pale gold bag",
"dark fuchsia bag:3 wavy blue bag, 5 faded indigo bag",
"dotted green bag:5 dull plum bag, 5 muted lavender bag, 3 faded magenta bag, 4 clear white bag",
"light salmon bag:2 muted purple bag, 5 shiny turquoise bag, 4 muted red bag, 5 posh red bag",
"plaid purple bag:1 muted indigo bag, 4 pale silver bag, 4 dull crimson bag, 1 posh cyan bag",
"light chartreuse bag:2 posh brown bag",
"dotted black bag:3 dull gray bag, 5 muted gray bag, 5 pale maroon bag, 1 vibrant green bag",
"mirrored teal bag:4 light gold bag, 5 striped maroon bag, 2 pale maroon bag",
"dotted coral bag:3 dull teal bag",
"shiny lime bag:3 mirrored gray bag",
"shiny chartreuse bag:x",
"clear red bag:4 dim tan bag, 4 dotted brown bag, 2 striped orange bag",
"clear magenta bag:3 pale blue bag, 2 pale crimson bag",
"faded black bag:5 dark turquoise bag",
"wavy violet bag:5 light purple bag",
"vibrant crimson bag:1 shiny gold bag, 1 dotted tomato bag, 1 plaid black bag, 1 drab olive bag",
"plaid violet bag:1 shiny tan bag, 3 muted gray bag, 4 drab chartreuse bag",
"vibrant lime bag:3 dark magenta bag, 2 dotted white bag, 4 muted tan bag",
"faded violet bag:2 drab red bag",
"plaid black bag:2 clear aqua bag, 2 wavy silver bag, 4 dim violet bag, 2 plaid red bag",
"dull orange bag:1 clear tan bag, 1 plaid crimson bag, 1 pale chartreuse bag",
"vibrant magenta bag:4 striped blue bag",
"plaid fuchsia bag:1 vibrant lime bag, 4 faded indigo bag, 2 wavy fuchsia bag, 1 dim purple bag",
"mirrored olive bag:1 dark teal bag, 1 pale brown bag, 1 light violet bag, 1 shiny yellow bag",
"wavy plum bag:5 vibrant cyan bag, 1 pale gold bag, 2 wavy gray bag, 5 pale gray bag",
"striped magenta bag:5 faded silver bag, 1 mirrored teal bag",
"light indigo bag:1 light olive bag",
"mirrored crimson bag:2 vibrant crimson bag",
"muted crimson bag:2 plaid olive bag",
"muted yellow bag:1 muted brown bag, 4 striped lavender bag, 1 bright violet bag",
"posh lavender bag:2 wavy coral bag, 3 light tan bag",
"striped indigo bag:4 dark brown bag",
"dotted red bag:4 pale olive bag, 3 dark teal bag, 1 posh fuchsia bag",
"plaid indigo bag:5 faded gold bag, 4 clear coral bag, 3 dull purple bag, 5 pale brown bag",
"plaid magenta bag:5 faded black bag, 3 drab aqua bag, 5 vibrant green bag",
"light coral bag:1 bright gray bag, 4 wavy orange bag, 2 drab coral bag, 1 dark coral bag",
"clear brown bag:4 plaid aqua bag, 4 plaid coral bag, 5 drab red bag",
"drab black bag:2 dotted white bag, 1 muted purple bag, 3 posh gold bag",
"dull magenta bag:1 dull tomato bag, 4 posh gray bag, 4 wavy white bag, 1 pale cyan bag",
"muted violet bag:3 posh chartreuse bag, 1 dotted magenta bag",
"vibrant turquoise bag:4 plaid brown bag, 5 drab indigo bag, 4 mirrored green bag",
"striped aqua bag:2 posh violet bag, 5 shiny blue bag, 3 pale tomato bag",
"light teal bag:4 faded cyan bag, 2 clear turquoise bag",
"clear turquoise bag:3 shiny aqua bag, 5 posh tomato bag",
"dark maroon bag:2 shiny gold bag, 5 faded green bag",
"vibrant beige bag:5 plaid turquoise bag, 2 shiny gold bag, 2 clear tan bag, 1 wavy black bag",
"muted chartreuse bag:2 muted white bag, 2 striped tan bag, 1 muted brown bag, 5 posh lime bag",
"pale maroon bag:5 pale teal bag, 4 dim violet bag, 5 posh teal bag",
"vibrant white bag:5 light bronze bag, 1 wavy silver bag",
"plaid olive bag:5 mirrored teal bag, 5 faded gray bag, 4 light olive bag",
"dull silver bag:5 clear cyan bag, 1 dim tan bag, 5 dim black bag",
"bright crimson bag:5 dotted indigo bag",
"muted teal bag:3 striped aqua bag, 4 dotted gray bag, 2 bright salmon bag",
"wavy salmon bag:5 posh tomato bag",
"bright purple bag:4 light maroon bag, 2 dotted violet bag",
"plaid green bag:3 faded black bag, 2 plaid red bag, 4 clear turquoise bag",
"wavy gold bag:1 bright white bag",
"drab violet bag:4 vibrant tomato bag",
"posh maroon bag:3 clear tan bag, 3 light gold bag, 1 dim lime bag",
"muted beige bag:4 clear white bag, 5 light maroon bag, 2 clear orange bag",
"dull turquoise bag:4 posh blue bag, 1 mirrored green bag, 5 dotted orange bag, 5 wavy fuchsia bag",
"shiny red bag:4 dark magenta bag",
"light turquoise bag:3 dark cyan bag",
"posh olive bag:3 clear green bag, 5 bright bronze bag, 5 light olive bag",
"dim chartreuse bag:5 vibrant plum bag",
"dark salmon bag:1 dotted orange bag, 3 light brown bag, 3 dotted chartreuse bag",
"dull teal bag:4 wavy gold bag, 5 faded red bag, 4 light turquoise bag",
"dark green bag:3 pale silver bag, 5 clear tan bag",
"bright cyan bag:2 striped maroon bag, 1 clear silver bag, 1 dark maroon bag",
"wavy crimson bag:3 wavy tan bag",
"mirrored white bag:4 mirrored teal bag, 2 muted silver bag",
"dark magenta bag:1 drab blue bag, 4 light white bag, 3 dark black bag",
"light gold bag:4 posh red bag, 1 striped maroon bag, 5 bright purple bag, 4 dotted violet bag",
"pale tomato bag:5 drab coral bag, 3 posh teal bag, 4 dotted blue bag",
"dull purple bag:4 posh gold bag",
"mirrored gold bag:3 mirrored teal bag, 1 striped maroon bag, 2 dotted indigo bag",
"dotted turquoise bag:2 dim violet bag",
"muted magenta bag:1 muted red bag",
"bright maroon bag:3 wavy fuchsia bag, 2 dark magenta bag, 2 dim maroon bag, 1 dotted teal bag",
"bright aqua bag:5 dim green bag, 2 striped tan bag, 1 faded olive bag",
"striped silver bag:5 striped aqua bag, 2 striped purple bag, 3 dim blue bag, 3 faded olive bag",
"light brown bag:4 posh red bag, 3 clear gold bag",
"dark brown bag:4 clear olive bag",
"dim crimson bag:4 dotted teal bag, 3 dark salmon bag",
"wavy black bag:3 drab coral bag, 1 striped purple bag, 2 light brown bag, 4 plaid red bag",
"striped coral bag:2 plaid blue bag, 5 drab tan bag, 5 light violet bag",
"dull blue bag:3 pale gold bag, 1 posh crimson bag",
"pale blue bag:4 dotted blue bag, 3 muted beige bag, 1 faded red bag",
"mirrored yellow bag:4 muted cyan bag, 2 mirrored tan bag",
"dim maroon bag:1 muted aqua bag",
"drab plum bag:2 shiny magenta bag",
"clear maroon bag:2 drab orange bag, 3 shiny red bag, 1 clear brown bag",
"muted red bag:5 pale teal bag, 3 dim fuchsia bag, 1 light maroon bag",
"dark plum bag:5 light salmon bag, 4 dim olive bag",
"faded indigo bag:1 mirrored red bag, 3 faded lime bag",
"bright coral bag:3 posh gold bag, 3 vibrant crimson bag",
"dark indigo bag:5 faded silver bag, 2 dull tomato bag",
"drab white bag:5 light silver bag",
"vibrant violet bag:2 pale gray bag, 4 bright white bag, 3 light aqua bag",
"mirrored maroon bag:1 pale cyan bag, 4 clear bronze bag",
"wavy chartreuse bag:1 bright brown bag, 4 dim lime bag",
"dull brown bag:3 bright olive bag",
"vibrant yellow bag:3 shiny white bag, 2 clear blue bag",
"posh bronze bag:1 light bronze bag",
"dim aqua bag:5 wavy yellow bag, 3 muted purple bag, 3 pale crimson bag",
"clear gray bag:4 faded coral bag, 1 striped violet bag, 5 pale crimson bag, 4 muted lavender bag",
"muted plum bag:4 mirrored cyan bag",
"dim lime bag:2 clear plum bag, 2 dim green bag, 5 posh tan bag",
"dim red bag:2 plaid brown bag",
"drab bronze bag:4 faded plum bag, 4 clear plum bag, 1 posh cyan bag, 1 dark cyan bag",
"shiny purple bag:5 posh beige bag, 4 pale fuchsia bag, 2 wavy brown bag, 2 shiny maroon bag",
"dull beige bag:1 mirrored indigo bag, 2 drab cyan bag, 1 dim fuchsia bag",
"wavy blue bag:4 dotted maroon bag, 3 light maroon bag",
"faded white bag:2 vibrant purple bag, 1 muted purple bag",
"pale teal bag:x",
"bright tan bag:3 clear indigo bag, 2 pale orange bag",
"dull crimson bag:3 pale maroon bag, 3 vibrant bronze bag",
"posh black bag:1 muted tomato bag",
"vibrant maroon bag:5 mirrored crimson bag, 4 wavy beige bag",
"dark lime bag:4 dim yellow bag, 1 pale beige bag, 1 vibrant beige bag",
"bright white bag:2 dark turquoise bag",
"faded plum bag:1 vibrant indigo bag, 5 dotted maroon bag, 1 vibrant bronze bag",
"pale violet bag:2 pale lavender bag, 4 light brown bag, 5 vibrant tomato bag",
"wavy purple bag:2 shiny tomato bag, 2 clear maroon bag, 3 posh bronze bag, 4 dull aqua bag",
"plaid yellow bag:4 pale tomato bag, 2 dotted magenta bag, 5 wavy violet bag",
"bright silver bag:5 light gold bag, 2 posh tan bag, 4 faded gray bag",
"dark orange bag:4 dull yellow bag, 5 dull salmon bag",
"wavy coral bag:5 dim lavender bag, 2 mirrored teal bag, 1 shiny chartreuse bag, 2 light gold bag",
"pale aqua bag:1 faded plum bag, 5 vibrant plum bag",
"dotted brown bag:2 light purple bag, 4 dim beige bag, 5 pale white bag",
"plaid blue bag:1 shiny red bag, 5 light silver bag, 5 clear orange bag",
"dim violet bag:3 posh teal bag",
"dull yellow bag:5 muted aqua bag",
"shiny yellow bag:5 muted aqua bag, 2 drab white bag, 5 muted purple bag",
"dotted maroon bag:4 dim green bag, 2 faded silver bag",
"bright brown bag:4 striped bronze bag",
"posh crimson bag:2 posh red bag, 1 dotted indigo bag, 4 muted red bag",
"dim orange bag:2 light tan bag, 4 dotted salmon bag",
"mirrored beige bag:4 dim bronze bag, 5 vibrant salmon bag, 4 dim maroon bag",
"shiny olive bag:5 dotted orange bag",
"wavy tan bag:1 wavy brown bag, 1 faded silver bag",
"mirrored magenta bag:5 drab teal bag, 3 striped bronze bag, 3 striped magenta bag, 5 dark tan bag",
"muted brown bag:1 light indigo bag, 4 dotted blue bag",
"vibrant aqua bag:1 shiny red bag, 5 wavy gold bag",
"dark violet bag:2 dim orange bag, 5 dark purple bag, 2 pale yellow bag",
"plaid teal bag:3 vibrant bronze bag",
"shiny gold bag:5 drab red bag, 2 mirrored green bag, 2 muted tomato bag, 1 striped magenta bag",
"wavy bronze bag:2 vibrant green bag, 2 plaid orange bag, 2 vibrant orange bag",
"dark tomato bag:4 posh indigo bag",
"drab red bag:x",
"clear silver bag:1 plaid olive bag",
"striped cyan bag:3 wavy silver bag, 2 faded indigo bag",
"dark purple bag:1 wavy violet bag, 5 clear olive bag, 3 drab indigo bag, 5 striped purple bag",
"dotted plum bag:4 vibrant purple bag, 3 muted lavender bag, 1 wavy coral bag",
"posh yellow bag:5 light salmon bag, 2 light bronze bag",
"dim tomato bag:3 pale white bag",
"drab lime bag:3 drab chartreuse bag, 4 clear silver bag, 4 drab aqua bag",
"plaid coral bag:2 bright olive bag",
"mirrored salmon bag:3 plaid green bag",
"faded chartreuse bag:2 light cyan bag, 5 pale tomato bag",
"pale crimson bag:5 bright white bag, 3 shiny turquoise bag",
"pale brown bag:4 bright silver bag",
"shiny bronze bag:5 dull chartreuse bag, 4 dotted gray bag, 3 shiny blue bag, 1 dull blue bag",
"faded red bag:2 muted gray bag",
"dark lavender bag:5 dim coral bag, 4 muted gray bag, 1 shiny yellow bag",
"faded purple bag:2 dotted white bag",
"mirrored silver bag:3 pale maroon bag, 2 pale cyan bag, 4 dark chartreuse bag, 3 bright plum bag",
"dull violet bag:1 dim coral bag, 3 wavy lavender bag",
"faded beige bag:4 plaid bronze bag, 1 light salmon bag, 2 light brown bag",
"vibrant orange bag:1 faded cyan bag, 2 vibrant olive bag, 2 bright plum bag",
"vibrant purple bag:5 dotted orange bag, 1 striped aqua bag, 4 clear white bag, 3 dim olive bag",
"faded crimson bag:1 clear lavender bag, 3 dim lavender bag, 3 dim cyan bag, 2 wavy tan bag",
"dark yellow bag:1 plaid silver bag, 3 wavy maroon bag",
"vibrant brown bag:5 dotted chartreuse bag, 4 clear silver bag, 4 dull lavender bag",
"wavy lavender bag:4 dull gray bag",
"bright green bag:5 striped gold bag",
"faded magenta bag:5 dull beige bag",
"posh white bag:2 dark coral bag",
"muted green bag:1 wavy lavender bag, 1 striped aqua bag",
"plaid turquoise bag:1 striped brown bag, 4 mirrored maroon bag",
"plaid lavender bag:4 striped tan bag, 2 posh brown bag, 5 shiny brown bag",
"pale fuchsia bag:5 light brown bag, 3 vibrant lime bag",
"light gray bag:3 drab violet bag",
"dim green bag:x",
"light olive bag:4 vibrant bronze bag",
"dotted aqua bag:5 muted red bag",
"vibrant fuchsia bag:5 dull crimson bag, 5 dotted violet bag",
"clear crimson bag:5 dotted tomato bag, 3 posh crimson bag, 5 vibrant magenta bag",
"pale orange bag:5 mirrored indigo bag, 5 muted purple bag, 4 plaid orange bag",
"mirrored lavender bag:4 dotted orange bag, 3 posh violet bag",
"dotted tan bag:5 mirrored gray bag",
"dim bronze bag:3 mirrored olive bag, 3 plaid magenta bag, 5 dim black bag, 2 drab blue bag",
"clear olive bag:3 bright purple bag, 4 dim lime bag, 5 dim fuchsia bag",
"dotted blue bag:1 dim green bag, 3 drab red bag, 2 posh gold bag",
"shiny gray bag:3 pale lavender bag, 1 clear gold bag, 2 drab violet bag, 2 clear bronze bag",
"bright plum bag:3 muted yellow bag, 4 posh chartreuse bag, 3 posh brown bag, 3 dim orange bag",
"shiny violet bag:5 dim coral bag",
"posh lime bag:3 plaid silver bag",
"light beige bag:5 pale yellow bag, 3 light bronze bag, 5 pale turquoise bag",
"drab gray bag:4 bright purple bag, 5 faded gold bag, 2 dim green bag",
"muted aqua bag:4 clear white bag",
"mirrored blue bag:2 vibrant green bag, 2 drab gray bag",
"posh magenta bag:2 striped magenta bag, 5 dim cyan bag, 5 plaid orange bag, 1 wavy black bag",
"dim yellow bag:2 muted purple bag, 1 striped black bag, 3 wavy coral bag",
"dull indigo bag:3 posh fuchsia bag, 1 dotted beige bag",
"posh gray bag:5 drab black bag",
"dark blue bag:4 dim gold bag, 3 drab olive bag, 1 light cyan bag, 2 light tomato bag",
"mirrored red bag:5 shiny white bag, 1 mirrored green bag, 4 wavy black bag, 1 dark brown bag",
"mirrored violet bag:3 dim tan bag, 4 dark fuchsia bag, 4 pale turquoise bag",
"shiny black bag:5 clear orange bag, 2 vibrant silver bag, 2 plaid maroon bag, 3 light olive bag",
"vibrant chartreuse bag:4 dull salmon bag, 3 bright beige bag, 1 faded blue bag, 2 plaid brown bag",
"dull cyan bag:3 faded green bag",
"bright gold bag:3 posh plum bag",
"vibrant olive bag:5 mirrored coral bag, 3 dotted lime bag, 5 drab blue bag, 2 dotted green bag",
"faded maroon bag:4 mirrored green bag, 2 light lime bag, 3 light bronze bag",
"vibrant red bag:2 posh lime bag, 1 dull maroon bag",
"dull bronze bag:5 vibrant chartreuse bag",
"vibrant bronze bag:2 vibrant tomato bag, 3 mirrored teal bag",
"pale black bag:1 muted silver bag, 5 mirrored teal bag, 2 shiny blue bag",
"dull maroon bag:1 clear cyan bag",
"dotted crimson bag:5 posh black bag, 1 dotted teal bag, 4 vibrant salmon bag, 4 shiny silver bag",
"striped tomato bag:5 drab tomato bag, 2 faded coral bag, 2 dim salmon bag",
"bright bronze bag:5 plaid red bag, 4 striped yellow bag",
"dark aqua bag:4 bright purple bag, 1 striped gold bag",
"striped teal bag:4 striped black bag, 3 clear indigo bag",
"dark olive bag:2 pale cyan bag, 5 mirrored tan bag",
"dark teal bag:1 posh gold bag, 1 plaid orange bag, 1 vibrant bronze bag, 1 mirrored teal bag",
"faded green bag:5 vibrant fuchsia bag, 3 dim olive bag",
"posh brown bag:4 drab lime bag, 2 mirrored fuchsia bag, 3 shiny lime bag, 2 dim violet bag",
"striped lavender bag:2 plaid red bag, 5 dark brown bag, 3 clear turquoise bag",
"shiny indigo bag:2 striped lavender bag, 1 light gray bag",
"plaid orange bag:1 pale teal bag, 5 dim violet bag, 5 vibrant bronze bag, 3 light maroon bag",
"dull salmon bag:1 striped bronze bag, 4 shiny aqua bag, 4 dark brown bag",
"plaid white bag:1 dim green bag",
"drab lavender bag:2 dotted maroon bag, 3 pale aqua bag, 1 light olive bag",
"striped olive bag:5 striped magenta bag",
"mirrored gray bag:2 dim lavender bag, 2 shiny chartreuse bag",
"dull coral bag:1 mirrored gold bag, 5 clear gold bag, 5 clear olive bag, 2 posh tomato bag",
"pale beige bag:2 dark indigo bag, 4 dim beige bag",
"posh teal bag:1 dim green bag, 3 dim fuchsia bag, 1 pale teal bag, 2 dotted indigo bag",
"mirrored turquoise bag:4 dim olive bag, 2 plaid tomato bag",
"dim turquoise bag:2 bright yellow bag, 1 striped lavender bag",
"light violet bag:4 faded gold bag, 3 clear plum bag, 1 dark teal bag",
"dark cyan bag:3 drab red bag, 4 pale maroon bag",
"shiny crimson bag:5 dotted turquoise bag, 1 vibrant fuchsia bag, 5 dotted lime bag, 2 wavy green bag",
"muted lime bag:2 light brown bag, 5 plaid tomato bag, 4 plaid aqua bag",
"vibrant tan bag:4 wavy fuchsia bag",
"wavy maroon bag:4 dull white bag, 5 dark crimson bag, 5 mirrored salmon bag, 4 vibrant purple bag",
"muted indigo bag:5 shiny red bag",
"clear violet bag:2 plaid green bag",
"drab teal bag:2 pale cyan bag, 1 shiny turquoise bag",
"wavy green bag:5 plaid indigo bag, 3 muted silver bag, 5 light brown bag",
"striped crimson bag:3 shiny aqua bag",
"drab purple bag:3 drab orange bag, 3 dark aqua bag, 1 bright lavender bag",
"plaid aqua bag:1 plaid tomato bag",
"striped green bag:2 vibrant tomato bag, 2 faded plum bag",
"drab tomato bag:4 posh black bag, 3 dull brown bag, 1 drab cyan bag",
"dotted bronze bag:1 clear indigo bag",
"pale white bag:5 mirrored green bag, 2 dark turquoise bag, 3 dull olive bag, 4 drab indigo bag",
"drab yellow bag:2 dotted orange bag, 4 light turquoise bag, 4 light salmon bag, 2 dotted tomato bag",
"pale green bag:3 muted gold bag, 3 shiny turquoise bag",
"dark tan bag:4 muted cyan bag, 5 dotted tomato bag, 2 dark indigo bag",
"plaid tan bag:4 vibrant olive bag, 1 plaid aqua bag, 3 dotted coral bag, 4 bright violet bag",
"shiny aqua bag:2 dull brown bag, 1 vibrant cyan bag, 2 dim lime bag, 5 light bronze bag",
"bright turquoise bag:2 plaid yellow bag, 3 posh lavender bag, 1 pale yellow bag",
"vibrant gold bag:1 clear tomato bag, 4 clear turquoise bag, 4 dark bronze bag",
"posh cyan bag:3 dotted green bag, 5 plaid tomato bag, 3 wavy crimson bag, 2 striped olive bag",
"clear salmon bag:3 plaid fuchsia bag, 5 muted bronze bag, 5 dull green bag, 2 pale brown bag",
"drab maroon bag:5 dull crimson bag, 2 shiny white bag, 5 light purple bag",
"clear tan bag:5 dull lime bag, 5 muted red bag, 2 clear cyan bag",
"pale gray bag:3 shiny white bag",
"vibrant teal bag:1 clear green bag, 1 dull beige bag",
"vibrant plum bag:4 muted red bag, 2 faded blue bag, 5 vibrant tomato bag",
"dark coral bag:2 plaid tomato bag, 1 bright yellow bag, 2 mirrored gray bag",
"wavy indigo bag:1 mirrored tan bag, 1 wavy lavender bag",
"dotted fuchsia bag:2 vibrant silver bag, 3 mirrored tan bag",
"muted gold bag:3 muted red bag, 1 clear olive bag",
"striped fuchsia bag:2 clear aqua bag, 4 mirrored coral bag, 3 muted gray bag, 2 dark beige bag",
"striped maroon bag:x",
"bright lavender bag:2 faded indigo bag, 1 dotted violet bag, 5 posh tomato bag, 3 clear indigo bag",
"posh gold bag:1 dim violet bag, 2 shiny chartreuse bag",
"drab olive bag:4 faded silver bag",
"pale chartreuse bag:4 striped teal bag",
"mirrored lime bag:5 dotted plum bag, 1 light yellow bag, 3 pale fuchsia bag",
"clear bronze bag:4 plaid brown bag",
"wavy tomato bag:4 faded lavender bag, 3 dull aqua bag, 1 drab green bag, 3 vibrant gray bag",
"dim brown bag:4 dull teal bag, 2 vibrant black bag, 1 mirrored gold bag",
"bright fuchsia bag:4 faded lavender bag, 1 dull crimson bag, 1 mirrored brown bag, 5 dark indigo bag",
"muted gray bag:1 dull olive bag",
"dull white bag:1 light maroon bag, 4 dark lavender bag, 2 posh red bag",
"dull black bag:5 dark green bag, 4 bright lime bag, 4 mirrored gray bag",
"dull tomato bag:4 dotted tomato bag",
"pale coral bag:1 mirrored white bag, 5 clear aqua bag, 4 dim blue bag",
"posh indigo bag:2 bright bronze bag",
"plaid gold bag:4 dark maroon bag, 4 shiny lavender bag, 1 plaid tomato bag, 3 bright yellow bag",
"plaid gray bag:4 muted bronze bag, 2 posh chartreuse bag, 5 pale tomato bag, 3 drab coral bag",
"dim beige bag:4 dim blue bag, 4 dark lavender bag",
"bright olive bag:x",
"clear aqua bag:4 wavy fuchsia bag, 5 dim green bag",
"posh violet bag:2 vibrant indigo bag, 3 posh tomato bag, 4 clear gold bag, 5 dim green bag",
"faded coral bag:4 light purple bag, 4 mirrored salmon bag, 5 pale maroon bag",
"dotted chartreuse bag:2 clear aqua bag, 4 plaid coral bag",
"striped orange bag:5 bright tan bag, 5 pale white bag, 5 mirrored lavender bag",
"bright tomato bag:5 muted white bag",
"shiny silver bag:1 dotted orange bag, 2 light olive bag, 1 striped gold bag",
"striped yellow bag:1 shiny turquoise bag",
"faded aqua bag:5 shiny cyan bag, 3 dotted indigo bag, 4 faded fuchsia bag",
"striped beige bag:1 bright white bag, 5 dim lavender bag, 5 striped black bag, 1 wavy black bag",
"shiny orange bag:4 dark aqua bag",
"striped white bag:3 vibrant fuchsia bag, 1 dotted teal bag, 5 dotted green bag, 2 shiny white bag",
"bright black bag:5 pale blue bag, 2 drab teal bag, 1 dull gray bag",
"shiny lavender bag:1 pale gold bag, 2 bright crimson bag, 2 pale maroon bag",
"shiny maroon bag:2 wavy white bag, 2 muted aqua bag, 3 plaid gold bag",
"drab cyan bag:4 posh crimson bag, 5 drab red bag, 5 bright purple bag",
"dark bronze bag:5 posh teal bag",
"shiny turquoise bag:2 shiny gold bag, 5 mirrored teal bag, 5 mirrored gray bag, 1 drab cyan bag",
"dark turquoise bag:1 dim violet bag, 5 mirrored teal bag",
"light lime bag:4 drab chartreuse bag",
"light yellow bag:5 wavy olive bag, 2 wavy gray bag, 4 bright red bag, 5 shiny violet bag",
"posh aqua bag:3 vibrant salmon bag",
"drab silver bag:3 pale tan bag",
"pale tan bag:3 wavy white bag",
"light white bag:4 wavy black bag, 2 dark teal bag, 2 faded blue bag",
"shiny teal bag:5 wavy gold bag",
"shiny tomato bag:3 faded violet bag",
"wavy brown bag:1 dim black bag, 1 bright yellow bag",
"dim tan bag:2 clear teal bag, 5 drab teal bag, 4 posh lime bag",
"faded cyan bag:1 pale plum bag, 4 posh gold bag, 4 posh yellow bag",
"dotted magenta bag:4 drab tomato bag, 5 drab yellow bag, 2 clear maroon bag",
"clear green bag:5 striped maroon bag, 4 shiny aqua bag",
"clear fuchsia bag:5 dotted chartreuse bag, 5 pale plum bag, 2 muted red bag",
"bright lime bag:3 dark salmon bag, 3 bright cyan bag, 4 striped black bag, 4 posh violet bag",
"bright violet bag:1 light olive bag, 2 dark coral bag, 1 dull beige bag, 5 plaid maroon bag",
"vibrant lavender bag:5 dim green bag, 1 plaid violet bag, 4 dotted coral bag",
"wavy silver bag:2 mirrored green bag, 4 clear olive bag, 5 dark beige bag, 5 plaid orange bag",
"clear orange bag:4 dotted orange bag, 3 bright silver bag, 5 dotted tomato bag, 4 striped purple bag",
"light crimson bag:5 striped teal bag, 1 striped coral bag, 1 pale tomato bag, 2 dark crimson bag",
"bright gray bag:3 posh tan bag",
"mirrored indigo bag:1 mirrored green bag",
"dull chartreuse bag:4 pale gold bag, 2 drab lavender bag, 3 shiny cyan bag",
"pale salmon bag:5 drab purple bag, 2 dark olive bag, 4 mirrored silver bag",
"bright indigo bag:5 striped beige bag, 5 shiny lime bag",
"dim lavender bag:5 striped maroon bag",
"bright magenta bag:2 plaid coral bag, 5 shiny aqua bag, 1 light purple bag",
"muted purple bag:4 shiny turquoise bag, 1 shiny chartreuse bag, 3 muted tomato bag, 1 dotted aqua bag",
"muted cyan bag:4 wavy black bag, 2 faded plum bag, 1 dull coral bag, 3 light tomato bag",
"shiny plum bag:5 pale gray bag, 3 vibrant aqua bag",
"dull lime bag:4 drab cyan bag, 1 posh gold bag, 4 bright purple bag, 3 posh tan bag",
"faded teal bag:3 bright purple bag, 4 dotted magenta bag, 4 plaid olive bag",
"clear chartreuse bag:2 dark brown bag, 1 pale lavender bag, 2 dark coral bag",
"dotted tomato bag:1 dim green bag, 2 posh tomato bag",
"pale silver bag:2 pale teal bag, 4 light purple bag, 4 bright yellow bag, 4 clear plum bag",
"posh purple bag:2 faded tan bag, 3 clear aqua bag, 4 striped lavender bag, 3 dark teal bag",
"striped bronze bag:4 drab red bag, 5 mirrored gray bag",
"striped black bag:3 wavy coral bag, 3 faded blue bag, 5 bright olive bag, 2 dark bronze bag",
"dark chartreuse bag:5 posh tomato bag",
"muted white bag:2 mirrored gray bag, 5 dark cyan bag, 3 dotted indigo bag",
"clear indigo bag:3 dark coral bag, 1 pale green bag, 2 plaid orange bag, 4 dim lime bag",
"faded tan bag:3 dull purple bag, 2 dim orange bag",
"clear yellow bag:1 vibrant fuchsia bag, 5 faded silver bag, 5 faded black bag",
"dark gray bag:5 striped cyan bag",
"clear plum bag:2 drab indigo bag, 5 pale maroon bag",
"posh fuchsia bag:2 muted lavender bag, 5 posh red bag",
"vibrant black bag:1 posh gold bag, 1 shiny white bag",
"dim salmon bag:5 muted tan bag, 2 muted green bag, 2 pale bronze bag",
"faded brown bag:3 dim tan bag",
"mirrored brown bag:1 drab bronze bag, 3 wavy coral bag, 4 posh fuchsia bag",
"dim gold bag:2 mirrored lavender bag, 5 pale gray bag",
"faded fuchsia bag:3 wavy lavender bag, 5 shiny blue bag, 4 muted tomato bag",
"mirrored chartreuse bag:2 faded aqua bag, 4 dark coral bag, 4 wavy beige bag, 5 dark orange bag",
"muted fuchsia bag:3 light olive bag",
"dotted silver bag:5 dotted turquoise bag, 3 dark cyan bag, 2 plaid red bag",
"plaid lime bag:5 dull blue bag",
"dim gray bag:4 striped magenta bag, 3 dotted indigo bag, 2 dim violet bag, 3 light olive bag",
"wavy lime bag:2 bright salmon bag, 3 shiny cyan bag, 4 light gray bag, 4 shiny plum bag",
"striped lime bag:5 posh teal bag",
"dull red bag:3 mirrored tan bag, 3 dim tomato bag, 5 striped crimson bag",
"faded lavender bag:1 bright indigo bag, 1 dim purple bag, 5 mirrored gray bag, 4 clear cyan bag",
"wavy aqua bag:1 wavy gray bag, 3 dark crimson bag",
"faded turquoise bag:1 drab plum bag, 5 dull gray bag, 4 plaid black bag, 1 wavy crimson bag",
"dotted salmon bag:4 posh teal bag",
"clear coral bag:5 drab tomato bag",
"vibrant blue bag:4 dim lavender bag, 4 dark cyan bag",
"muted coral bag:5 vibrant olive bag, 1 clear plum bag, 1 clear blue bag",
"vibrant coral bag:5 vibrant silver bag, 2 plaid brown bag, 4 wavy brown bag",
"mirrored aqua bag:4 bright lavender bag, 4 striped lavender bag, 1 posh fuchsia bag",
"clear gold bag:1 posh tan bag, 1 dark beige bag, 5 striped gold bag",
"dull aqua bag:4 dull plum bag, 2 light indigo bag",
"clear cyan bag:5 light maroon bag, 5 posh tan bag, 3 dim lavender bag",
"dotted olive bag:1 mirrored maroon bag, 2 dotted red bag, 4 drab lime bag",
"wavy yellow bag:4 light silver bag, 4 dotted orange bag",
"faded salmon bag:1 shiny lavender bag, 4 muted tomato bag, 3 plaid coral bag, 3 pale green bag",
"dim blue bag:2 dim black bag",
"faded tomato bag:3 shiny magenta bag",
"light magenta bag:5 dim olive bag, 3 muted lavender bag",
"muted turquoise bag:4 posh gold bag, 2 wavy beige bag, 3 posh magenta bag",
"light purple bag:3 light maroon bag",
"pale indigo bag:2 light green bag, 5 plaid bronze bag",
"dim fuchsia bag:x",
"plaid chartreuse bag:3 shiny silver bag, 1 posh teal bag",
"plaid salmon bag:5 drab lime bag, 4 light aqua bag, 2 striped tan bag",
"drab coral bag:x",
"dotted gold bag:2 clear teal bag, 2 posh salmon bag, 1 plaid green bag, 5 muted tomato bag",
"dull olive bag:2 dim lavender bag",
"dotted purple bag:5 vibrant white bag, 5 wavy black bag",
"dark crimson bag:4 posh chartreuse bag, 3 muted green bag, 3 dull plum bag, 5 muted beige bag",
"mirrored tomato bag:2 clear crimson bag, 4 mirrored indigo bag, 2 muted black bag, 2 dark gray bag",
"muted blue bag:5 pale brown bag",
"wavy beige bag:5 plaid red bag",
"muted black bag:3 muted magenta bag, 2 clear tomato bag, 1 pale red bag",
"mirrored bronze bag:5 bright olive bag, 5 vibrant cyan bag, 2 drab cyan bag",
"vibrant green bag:2 dull brown bag, 4 wavy white bag, 3 pale teal bag, 4 dark bronze bag",
"dotted orange bag:5 light gold bag, 5 vibrant tomato bag, 3 light silver bag, 4 drab cyan bag",
"clear purple bag:4 dull fuchsia bag",
"mirrored green bag:2 muted red bag, 2 dim lavender bag",
"wavy red bag:1 posh yellow bag, 2 shiny coral bag",
"drab chartreuse bag:5 dull purple bag, 2 bright purple bag, 3 faded silver bag, 4 muted lavender bag",
"dim indigo bag:1 light red bag, 4 wavy olive bag",
"drab crimson bag:5 muted indigo bag, 5 vibrant crimson bag",
"wavy olive bag:3 light black bag, 2 wavy plum bag",
"dark silver bag:4 dull fuchsia bag, 3 dotted chartreuse bag",
"pale olive bag:1 dark purple bag, 1 drab yellow bag, 1 vibrant coral bag",
"posh silver bag:4 faded magenta bag, 5 muted coral bag, 4 posh cyan bag, 2 faded gray bag",
"clear white bag:4 shiny blue bag",
"light silver bag:3 mirrored green bag, 2 muted red bag, 1 muted tomato bag, 3 clear olive bag",
"faded gray bag:5 dim green bag, 5 pale teal bag, 4 posh crimson bag, 3 dotted indigo bag",
"clear teal bag:2 posh chartreuse bag, 2 posh blue bag",
"dull green bag:5 muted tan bag, 3 faded gray bag, 2 dark tan bag",
"dotted yellow bag:1 dim aqua bag, 5 dotted blue bag, 1 plaid teal bag, 2 dim salmon bag",
"dotted indigo bag:1 muted red bag",
"pale gold bag:1 mirrored green bag, 2 faded gray bag, 4 drab olive bag",
"pale magenta bag:1 pale gray bag",
"drab orange bag:4 dull beige bag, 1 dim gray bag",
"light maroon bag:x",
"dim silver bag:2 dull olive bag, 2 muted lavender bag, 5 dark fuchsia bag, 5 dotted tan bag",
"shiny magenta bag:5 light purple bag",
"shiny green bag:2 dim green bag, 1 pale plum bag, 2 striped teal bag",
"drab magenta bag:1 plaid yellow bag, 3 bright crimson bag, 4 shiny salmon bag",
"shiny salmon bag:4 dark bronze bag, 1 pale aqua bag, 5 posh red bag, 2 light gold bag",
"mirrored cyan bag:2 bright olive bag, 2 bright aqua bag, 4 shiny turquoise bag",
"drab aqua bag:1 drab olive bag, 5 shiny white bag, 2 dim gray bag",
"wavy white bag:1 plaid red bag",
"clear black bag:1 dim fuchsia bag, 5 pale white bag, 3 drab fuchsia bag",
"dotted cyan bag:3 wavy aqua bag, 4 shiny brown bag, 4 faded tan bag",
"dim magenta bag:4 striped orange bag, 2 mirrored turquoise bag, 3 vibrant turquoise bag, 3 pale chartreuse bag",
"faded silver bag:5 dim fuchsia bag, 2 bright purple bag",
"faded olive bag:3 dull lavender bag, 2 striped salmon bag, 1 bright yellow bag",
"faded lime bag:4 posh tan bag, 4 dotted lavender bag, 3 striped magenta bag",
"dark white bag:2 bright beige bag, 3 shiny chartreuse bag",
"striped brown bag:5 muted lavender bag",
"dotted lime bag:1 mirrored green bag, 4 dotted chartreuse bag, 2 shiny cyan bag, 1 bright purple bag",
"bright beige bag:4 dull gray bag, 3 wavy violet bag, 5 light silver bag, 5 drab white bag",
"dark beige bag:3 light gold bag, 1 muted tomato bag, 4 pale teal bag, 4 posh crimson bag",
"dim olive bag:4 dark cyan bag",
"plaid plum bag:1 clear tan bag, 4 posh brown bag",
"wavy magenta bag:4 dotted plum bag, 2 dull tan bag",
"drab gold bag:4 dark cyan bag, 2 clear yellow bag",
"muted orange bag:2 faded tan bag, 5 vibrant salmon bag",
"pale yellow bag:3 light turquoise bag, 3 plaid maroon bag, 2 dull salmon bag",
"plaid tomato bag:2 dark beige bag",
"dim purple bag:5 posh salmon bag, 2 dim lime bag, 2 dotted white bag",
"bright red bag:4 dark teal bag, 3 shiny cyan bag",
"bright salmon bag:4 pale aqua bag, 3 clear orange bag, 3 plaid black bag, 5 faded aqua bag",
"plaid crimson bag:4 plaid tan bag, 4 dim aqua bag",
"striped violet bag:2 dotted olive bag, 2 dotted red bag, 4 shiny gold bag",
"vibrant tomato bag:3 dim lime bag",
"drab turquoise bag:5 shiny purple bag, 1 light green bag, 1 pale chartreuse bag",
"wavy turquoise bag:1 dark teal bag, 5 shiny fuchsia bag, 4 muted brown bag, 4 bright green bag",
"striped plum bag:3 bright chartreuse bag, 1 dotted violet bag, 1 posh maroon bag",
"mirrored plum bag:4 plaid indigo bag, 5 dotted white bag",
"muted salmon bag:5 faded magenta bag, 3 plaid blue bag",
"shiny brown bag:3 drab salmon bag",
"drab blue bag:3 drab olive bag, 5 muted red bag, 2 bright purple bag",
"striped gray bag:3 clear olive bag, 2 muted coral bag",
"bright yellow bag:2 dull olive bag, 5 dark turquoise bag, 5 posh teal bag",
"dim plum bag:2 dim cyan bag, 5 vibrant crimson bag",
"muted lavender bag:2 clear bronze bag",
"muted silver bag:3 vibrant salmon bag, 5 muted cyan bag, 1 dotted black bag",
"mirrored orange bag:2 dull olive bag, 4 striped beige bag, 3 shiny aqua bag, 2 striped salmon bag",
"dim teal bag:2 drab blue bag",
"plaid brown bag:1 pale maroon bag, 4 light salmon bag, 1 vibrant indigo bag, 5 clear cyan bag",
"bright chartreuse bag:4 plaid coral bag, 2 dull crimson bag, 3 plaid aqua bag, 2 faded blue bag",
"dotted gray bag:1 dotted indigo bag, 2 posh crimson bag",
"drab indigo bag:1 dotted violet bag, 1 dim fuchsia bag, 4 muted red bag, 4 striped maroon bag",
"plaid bronze bag:3 drab plum bag, 1 posh violet bag, 2 dark tan bag, 3 plaid white bag",
"striped salmon bag:3 clear brown bag",
"dull lavender bag:4 pale green bag",
"dull gray bag:4 drab indigo bag, 4 light salmon bag, 2 plaid coral bag, 3 striped magenta bag",
"mirrored purple bag:2 vibrant brown bag, 1 plaid teal bag, 4 drab red bag, 4 plaid turquoise bag",
"dull gold bag:3 drab teal bag",
"light fuchsia bag:2 clear tan bag, 1 posh tan bag",
"dim white bag:1 bright beige bag",
"light green bag:1 dotted red bag, 4 muted gray bag, 5 dotted orange bag, 3 dim chartreuse bag",
"bright teal bag:5 bright bronze bag, 2 pale green bag",
"striped purple bag:1 dark beige bag",
"muted tan bag:4 pale silver bag, 2 bright lavender bag, 4 drab cyan bag",
"light blue bag:5 drab white bag, 1 pale olive bag",
"dim cyan bag:1 wavy fuchsia bag, 5 posh teal bag",
"striped chartreuse bag:4 bright beige bag, 1 muted lavender bag",
"light lavender bag:2 posh lavender bag, 1 dim lavender bag",
"striped gold bag:1 posh salmon bag, 3 mirrored gray bag, 1 faded silver bag",
"light orange bag:4 dark black bag",
"plaid silver bag:5 posh salmon bag, 3 vibrant tomato bag",
"dotted white bag:3 dim fuchsia bag, 4 shiny gold bag, 2 bright olive bag, 4 muted purple bag",
"faded bronze bag:3 pale green bag, 3 light yellow bag, 1 clear teal bag",
"striped turquoise bag:4 mirrored aqua bag, 2 wavy orange bag, 1 pale lavender bag, 4 drab aqua bag",
"clear lime bag:1 plaid green bag, 3 pale gold bag, 2 bright gray bag",
"drab salmon bag:3 dull tomato bag",
"plaid red bag:5 pale brown bag",
"posh coral bag:2 dim violet bag, 4 dotted teal bag, 2 plaid red bag, 4 muted green bag",
"light bronze bag:4 light purple bag",
"faded orange bag:2 light teal bag",
"dotted lavender bag:2 light olive bag, 3 muted tomato bag",
"bright orange bag:3 light gray bag, 4 striped purple bag, 5 dull tomato bag",
"mirrored coral bag:3 faded gray bag, 5 pale green bag, 4 pale aqua bag, 4 muted bronze bag",
"dull plum bag:4 posh crimson bag, 4 clear cyan bag, 4 shiny white bag, 2 dotted maroon bag",
"shiny blue bag:5 dim lime bag, 2 dim gray bag, 5 dark cyan bag, 3 posh teal bag",
"mirrored fuchsia bag:4 muted tomato bag, 5 dotted chartreuse bag, 1 light red bag, 2 bright yellow bag",
"dotted teal bag:1 dotted gray bag, 1 muted brown bag",
"mirrored tan bag:2 clear aqua bag, 4 dim violet bag, 1 wavy gray bag",
"posh chartreuse bag:2 faded blue bag, 4 dark coral bag, 2 light maroon bag, 5 dark purple bag",
"shiny tan bag:1 wavy salmon bag, 2 shiny red bag, 5 clear coral bag, 3 wavy gold bag",
"vibrant salmon bag:3 clear brown bag, 3 pale gold bag, 5 clear blue bag",
"plaid beige bag:5 vibrant lavender bag, 2 dim brown bag, 4 dull yellow bag",
"muted olive bag:3 vibrant blue bag, 5 shiny crimson bag, 5 pale beige bag, 2 dotted chartreuse bag",
"clear beige bag:4 drab coral bag, 4 dark maroon bag, 1 light indigo bag",
"dull fuchsia bag:2 pale magenta bag, 1 dotted indigo bag",
"dark gold bag:3 posh crimson bag, 3 mirrored lavender bag",
"pale plum bag:1 light bronze bag, 5 dotted violet bag, 2 dark salmon bag",
"drab fuchsia bag:4 dull brown bag, 5 muted bronze bag",
"mirrored black bag:1 muted silver bag, 3 plaid gray bag, 4 bright purple bag",
"posh blue bag:3 dull beige bag, 5 dull olive bag",
"posh beige bag:3 vibrant turquoise bag, 3 dotted lime bag",
"light aqua bag:2 mirrored teal bag, 1 vibrant lime bag, 1 dim olive bag",
"muted tomato bag:5 dim lavender bag",
"dim coral bag:4 shiny magenta bag, 4 drab violet bag, 5 clear brown bag."]

targetbag = ["shiny gold bag"]
answer = 0
saw = set()

def findcansee(bagsToCheck, multipliers, ctr):
    #print(bagsToCheck)
    #print(multipliers)
    checkBags = []
    addToContent = []
    contentList = []
    checkBag = ""
    currMul = []
    newMuls = []
    for current in range(len(bagsToCheck)): # Check bags 
        currMul = multipliers[current]
        checkBag = bagsToCheck[current]
        for x in range(len(inpt)):
            contents = []
            currBag = inpt[x]
            contents = currBag[currBag.index(":"):]
            contentsList = contents.split(", ")
            for item in contentList:
                addToContent.append(item[:contentsList.index(" ")])

            currBag = currBag[:currBag.index(":")]
            if currBag == checkBag:
                break
        # Find Multiplyers and bags list under current
        for z in range(len(contentsList)):
            bag = contentsList[z]
            if bag[1] == "x":
                pass
            elif bag[0] == ":":
                newMuls.append(int(bag[1: bag.index(" ")])*currMul)
                ctr += int(bag[1: bag.index(" ")])*currMul
            else:
                newMuls.append(int(bag[:bag.index(" ")])*currMul)
                ctr += int(bag[:bag.index(" ")])*currMul

            if bag[1] != "x":
                bag = bag[bag.index(" ")+1:]
                checkBags.append(bag)
                contentsList[z] = bag
        for content in contentsList:
            if content != ":x":
                print("\"" + checkBag +"\"" + "->" + "\"" + content + "\"")
                
    if len(newMuls) == 0:
        #print(ctr)
        return ctr  
    return findcansee(list(checkBags), newMuls, ctr)

print("digraph G {")
answer = findcansee(targetbag, [1], 0)
print("}")
print("Bags =",answer)

